schema_version = "1.0.0"

id = "diffused_texture_addon"
version = "0.1.0"
name = "DiffusedTexture"
tagline = "Generate Diffuse Textures on Meshes with Stable Diffusion"
maintainer = "Frederik Hasecke <frederik@hasecke.eu>"
type = "add-on"

website = "https://github.com/FrederikHasecke/diffused-texture-addon/"
tags = ["Material", "Paint"]

blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]

platforms = ["windows-x64", "linux-x64"]

[permissions]
network = "Download models from huggingface.co"
files = "Load/save renderings and textures from/to disk"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".git/",
  "*.zip",
  "*.tar.gz",
  ".github/",
  ".vscode/",
  ".ruff_cache/",
  "documentation/",
  "tests/",
  "images/",
  "scratchbook/",
  "*.md",
  "LICENSE",
  "NOTICE",
  "tests/",
  "pytest.ini",
  ".pytest_cache/",
  "Dockerfile",
  "pyproject.toml",
  "requirements.txt",
  "requirements-dev.txt",
  "wheels_dev/",
  "wheels-dev/"
]