[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py311"
select = ["ALL"]
ignore = ["D400", "D100", "D104", "N801"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"