[project]
name = "diffused_texture_addon"
version = "0.2.0"
description = "A Blender Addon for Generating Diffuse Textures on Meshes with Stable Diffusion"
authors = [{ name = "Frederik Hasecke" }]
requires-python = ">=3.11,<3.14,!=3.12.*"
dependencies = [
    "numpy>=1.26,<2.0; python_version < '3.13'",
    "numpy>=2.3,<2.4; python_version >= '3.13'",
    "pillow==12.2.0",
    "opencv-python-headless==4.11.0.86; python_version < '3.13'",
    "opencv-python-headless>=4.13.0.92; python_version >= '3.13'",
    "diffusers>=0.38",
    "transformers>=5.8.1", # TODO(Frederik): https://github.com/huggingface/diffusers/issues/12436#issuecomment-3375629264
    "accelerate>=1.13.0",
    "safetensors>=0.8.0rc0",
    "peft>=0.19.1",
]

[dependency-groups]
dev = [
  "torch",
  "bpy==5.1.0; python_version >= '3.13' and ((sys_platform == 'win32' and platform_machine == 'AMD64') or (sys_platform == 'linux' and platform_machine == 'x86_64'))",
  "pytest>=9.0.3",
  "pytest-xdist>=3.6.1",
  "pytest-mock>=3.15.1",
  "coverage>=7.14.0",
  "ruff>=0.15.12",
  "ty",
  "dotenv>=0.9.9",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu130", marker = "sys_platform == 'win32' or sys_platform == 'linux'" }
]

[tool.uv]
override-dependencies = [
  "numpy>=2.3,<2.4; python_version >= '3.13'",
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true


[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py313"
exclude = [
    "scratchbook/",
    "tests/"
]

[tool.ruff.lint]
select = ["ALL"]
ignore = ["TD002", "TD003", "D100", "D103", "D104", "D400", "N801", "N999", "INP001", "TID252", "RUF012","PLC0415", "FIX002"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"

[tool.mypy]
python_version = "3.13"
strict = true
ignore_missing_imports = true

[tool.ty.rules]
unresolved-attribute = "ignore"
invalid-assignment = "ignore"
unresolved-import = "ignore"
