name: DiffusedTexture Addon CI

on:
  push:
    tags:
      - 'v*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install ruff
      - run: ruff . 


  build:
    runs-on: ubuntu-latest
    needs: lint  # add test when enabled
    steps:
      - uses: actions/checkout@v3
      - name: Build Blender addon zip
        uses: BlenderKit/blender-addon-build-action@v1
        with:
          name: 'diffused_texture_addon'
          name-suffix: 'commit-hash'
          build-command: ''
          build-location: '.'  # zips the repo root
          exclude-files: '.git;.github;.vscode;tests;__pycache__'
      - name: Upload addon package
        uses: actions/upload-artifact@v4
        with:
          name: addon-package
          path: diffused_texture_addon*.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Download built package
        uses: actions/download-artifact@v4
        with:
          name: addon-package
      - name: Create GitHub Release
        id: ghrel
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: '*.zip'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
