name: Diffused Texture Addon Release

on:
  push:
    branches: [ master, v0-redesign ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (optional; falls back to blender_manifest.toml)'
        required: false
        default: ""

permissions:
  contents: write

env:
  PYTHON_VERSION: '3.11'

jobs:

  # 1) Lint
  lint:
    name: Ruff lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: |
            requirements-dev.txt
            pyproject.toml

      - name: Install lint deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt || true; fi
          pip install ruff

      - name: Ruff check
        run: ruff check . --output-format=github --config pyproject.toml

  # # 2) Tests
  # test:
  #   name: Pytest
  #   needs: lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ env.PYTHON_VERSION }}
  #         cache: 'pip'
  #         cache-dependency-path: |
  #           requirements-dev.txt
  #           pyproject.toml

  #     - name: Install test deps
  #       run: |
  #         python -m pip install --upgrade pip
  #         if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; else pip install pytest; fi
  #         # If your tests import the package, this helps (won't fail the job if not a buildable package)
  #         pip install -e . || true

  #     - name: Run pytest
  #       run: |
  #         set -e
  #         pytest -q || rc=$?
  #         if [ "${rc:-0}" -eq 5 ]; then
  #           echo "No tests collected. Skipping."
  #           exit 0
  #         else
  #           exit "${rc:-0}"
  #         fi

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Stage clean build dir
        run: |
          rm -rf dist/addon && mkdir -p dist/addon
          rsync -a --delete \
            --exclude='.git/' --exclude='.github/' --exclude='__pycache__/' \
            --exclude='.vscode/' --exclude='.ruff_cache/' --exclude='.pytest_cache/' \
            --exclude='documentation/' --exclude='tests/' --exclude='images/' \
            --exclude='scratchbook/' --exclude='*.md' --exclude='LICENSE' \
            --exclude='NOTICE' --exclude='Dockerfile' --exclude='pyproject.toml' \
            --exclude='requirements*.txt' \
            --exclude='wheels*/' \
            ./ dist/addon/
      - name: Build addon
        uses: blenderkit/blender-addon-build@main
        with:
          name: diffusedtexture-addon
          do-checkout: 'false'
          build-location: 'dist/addon'
          exclude-files: ".git"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: diffusedtexture-addon-${{ github.run_number }}
          path: ./  # the action finds the produced zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4
      - name: Read version
        shell: bash
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            echo "REL_VER=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            VER=$(python3 -c 'import tomllib; print(tomllib.load(open("blender_manifest.toml","rb"))["version"])')
            echo "REL_VER=$VER" >> $GITHUB_ENV
          fi
      - uses: actions/download-artifact@v4
        with:
          name: diffusedtexture-addon-${{ github.run_number }}
          path: out
      - name: Normalize filename
        shell: bash
        run: |
          f=$(find out -maxdepth 1 -name '*.zip' -print -quit)
          mv "$f" "out/diffusedtexture-addon-v${REL_VER}.zip"
          ls -lh out
      - uses: softprops/action-gh-release@v2
        with:
          draft: true
          name: DiffusedTextureAddon v${{ env.REL_VER }}
          tag_name: v${{ env.REL_VER }}
          files: out/diffusedtexture-addon-v${{ env.REL_VER }}.zip